'use client'

import { useState, type ReactNode } from 'react'
import Link from 'next/link'
import {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  Calendar,
  Check,
  Coins,
  CreditCard,
  Hash,
  Receipt,
  Repeat,
  Scale,
  Tag,
  Wallet,
} from 'lucide-react'
import { useTranslations } from 'next-intl'
import { useShowCents } from '@/lib/preferences-context'
import {
  getCategoryName,
  getSubcategoryName,
} from '@/lib/categories/display'
import type { CategorySliceInput } from '@grana/money-logic'
import type { FinancialMovement, MovementReviewFlag } from '@/lib/transactions/movements'
import type { TransactionWithDetails } from '@/lib/transactions/types'
import type { ExpenseReimbursementVM } from '@/lib/transactions/queries'
import type { MovementSharedInfo } from '@/lib/shared/queries'
import type { Household } from '@/lib/shared/types'
import { resolveTone } from '@/lib/transactions/components/tone'
import { resolveContextVariant } from '@/lib/transactions/components/resolve-context-variant'
import { Alert } from '@/components/ui/alert'
import { Drawer } from '@/components/ui/drawer'
import type { CategoryWithSubcategories } from '@/lib/categories/types'
import {
  MovementForm,
  type MovementEditContext,
} from '@/lib/transactions/components/movement-form'
import { useMovementDrawer } from '@/lib/transactions/movement-drawer-context'

import { DetailTopbar } from './detail/detail-topbar'
import { DetailActions } from './detail/detail-actions'
import { DetailHero } from './detail/detail-hero'
import { Glance, Chip, StatusDot } from './detail/glance'
import { TilePaymentMethod } from './detail/tile-payment-method'
import { TileDetail, type DetailRowSpec } from './detail/tile-detail'
import { TileDescription } from './detail/tile-description'
import { TileMonthWeight } from './detail/tile-month-weight'
import { TileInstallments } from './detail/tile-installments'
import { TileShareYours, TileDividedAmong } from './detail/tile-shared'
import { TileReimbursementNet } from './detail/tile-reimbursement-net'
import { TileRecurrence, TileRecurrenceHistory } from './detail/tile-recurrence'
import { TileTransferFlow, TileTransferCallout } from './detail/tile-transfer-flow'
import {
  detailToneFromTone,
  fmtMoney,
  formatLongDate,
  formatPeriodLabel,
  formatShortDate,
  toneVars,
} from './detail/helpers'
import { resolveCategoryWeight, resolveIncomeWeight } from './detail/month-weight'
import type { RecurrenceSummaryVM } from './detail/recurrence-summary'

const heroIcon = (movement: FinancialMovement): ReactNode => {
  if (movement.category_icon) return movement.category_icon
  switch (movement.kind) {
    case 'transfer':
    case 'exchange':
      return <ArrowLeftRight size={38} strokeWidth={1.8} aria-hidden />
    case 'adjustment':
      return <Scale size={38} strokeWidth={1.8} aria-hidden />
    case 'card_payment':
      return <CreditCard size={38} strokeWidth={1.8} aria-hidden />
    case 'reimbursement':
      return <Receipt size={38} strokeWidth={1.8} aria-hidden />
    default:
      return <Tag size={38} strokeWidth={1.8} aria-hidden />
  }
}

const backFor = (from: string | undefined): string => {
  if (from?.startsWith('account:')) return `/accounts/${from.slice('account:'.length)}`
  if (from?.startsWith('card:')) return `/cards/${from.slice('card:'.length)}`
  return '/transactions'
}

type Props = {
  transaction: TransactionWithDetails
  movement: FinancialMovement
  installmentParent?: TransactionWithDetails | null
  installmentSiblings?: TransactionWithDetails[] | null
  reimbursements?: ExpenseReimbursementVM[]
  from?: string
  /** Whether the current user owns this movement (its payer). A shared movement is
   * readable cross-user but only its owner may edit/delete it. Defaults to true. */
  canManage?: boolean
  edit?: MovementEditContext | null
  editCategories?: CategoryWithSubcategories[]
  editHousehold?: Household | null
  sharedInfo?: MovementSharedInfo | null
  paymentComposition?: { paidARS: number; paidUSD: number } | null
  /** Month category/income slices for the movement's currency (Peso en el mes). */
  monthWeightSlices?: CategorySliceInput[] | null
  /** Recurrence summary when the movement was generated by a rule. */
  recurrence?: RecurrenceSummaryVM | null
  /** Resolved card-period label ("Mayo 2026") for the context note. */
  contextPeriodLabel?: string
}

export const GlobalTransactionDetail = ({
  transaction,
  movement,
  installmentParent,
  installmentSiblings,
  reimbursements = [],
  from,
  canManage = true,
  edit,
  editCategories,
  editHousehold = null,
  sharedInfo,
  paymentComposition = null,
  monthWeightSlices = null,
  recurrence = null,
  contextPeriodLabel,
}: Props) => {
  const showCents = useShowCents()
  const movementDrawer = useMovementDrawer()
  const editHouseholdResolved = movementDrawer?.household ?? editHousehold
  const t = useTranslations('transactions')
  const tDetail = useTranslations('transactions.detail')
  const tRoot = useTranslations()
  const [editOpen, setEditOpen] = useState(false)
  const canUseEditDrawer = edit != null && editCategories != null

  const isPendingReimbursement =
    movement.kind === 'reimbursement' && movement.state !== 'received'
  const tone = resolveTone(movement.kind, movement.sign, isPendingReimbursement)
  const detailTone = detailToneFromTone(tone)

  // Nota contextual (consumo de tarjeta sin impactar disponible, reintegro
  // pendiente, etc.): info real que las tiles no cubren. Reusa el resolver
  // existente y se muestra como Alert bajo el hero.
  const contextVariant = resolveContextVariant(movement, transaction)
  const periodLabel =
    contextPeriodLabel ?? formatPeriodLabel(transaction.period_payments?.[0]?.period ?? null)
  const contextCopy = contextVariant
    ? tDetail(`context.${contextVariant.replace(/-/g, '_')}`, { periodo: periodLabel })
    : null

  const actionAccountId = transaction.account_id ?? installmentSiblings?.[0]?.account_id ?? null
  // A single cuota (parent_id set) is never edited on its own — amount/date/
  // category belong to the parent (madre). It has NO edit/delete action; the
  // only affordance is a note linking to the original purchase (the madre).
  const installmentParentHref =
    transaction.parent_id != null ? `/transactions/${transaction.parent_id}` : null
  // Only the owner (payer) can edit/delete. A shared movement paid by the other
  // member is read-only here even though it's visible via the household RLS.
  const canEdit =
    canManage &&
    actionAccountId != null &&
    transaction.status !== 'paid' &&
    installmentParentHref == null
  const canDelete =
    canManage && actionAccountId != null && !transaction.parent_id && transaction.status !== 'paid'

  const categoryLabel = transaction.category ? getCategoryName(transaction.category, tRoot) : null
  const subcategoryLabel = transaction.subcategory
    ? getSubcategoryName(transaction.subcategory, tRoot)
    : null
  const money = (amount: number, currency: 'ARS' | 'USD' = movement.currency_code) =>
    fmtMoney(amount, currency, showCents)

  const reviewLabel: Record<MovementReviewFlag, string> = {
    missing_category: t('review_flags.missing_category'),
  }

  // ── Variant ───────────────────────────────────────────────────────────────
  const isTransferLike = movement.kind === 'transfer' || movement.kind === 'exchange'
  const isInstallment =
    movement.kind === 'installment_purchase' ||
    (installmentSiblings != null && installmentSiblings.length > 0)
  const hasReimbursements = movement.kind === 'expense' && reimbursements.length > 0
  const isShared = sharedInfo != null && movement.kind === 'expense'
  const isIncome = movement.kind === 'income'
  const isExpense = movement.kind === 'expense' || movement.kind === 'installment_purchase'

  // ── Hero ────────────────────────────────────────────────────────────────────
  const heroTitle =
    movement.description ?? movement.title ?? categoryLabel ?? t(`types.${transaction.type}`)

  const flowLine: ReactNode = (() => {
    if (isTransferLike) return tDetail('flow.transfer')
    if (recurrence) return tDetail('flow.recurrence')
    if (isInstallment) return tDetail('flow.installments', { count: movement.kind === 'installment_purchase' ? (movement.installments_total ?? installmentSiblings?.length ?? 0) : (installmentSiblings?.length ?? 0) })
    if (isShared) return tDetail('flow.shared', { count: (sharedInfo!.bySplit.length ?? 0) + 1 })
    if (hasReimbursements) return tDetail('flow.reimbursement')
    if (isIncome) return tDetail('flow.income')
    if (movement.kind === 'expense') return tDetail('flow.expense')
    return null
  })()

  const dateChip = (
    <Chip key="date">
      <Calendar size={14} strokeWidth={2} aria-hidden />
      {formatShortDate(movement.date)}
    </Chip>
  )
  const chips: ReactNode[] = [dateChip]
  if (isTransferLike) {
    chips.push(
      <Chip key="internal" tone>
        <ArrowLeftRight size={14} strokeWidth={2} aria-hidden />
        {tDetail('transfer.internal')}
      </Chip>,
    )
  } else {
    if (movement.account_name) {
      chips.push(
        <Chip key="method" tone>
          <Wallet size={14} strokeWidth={2} aria-hidden />
          {movement.account_name}
        </Chip>,
      )
    }
    if (categoryLabel) chips.push(<Chip key="cat">{categoryLabel}</Chip>)
    if (subcategoryLabel) chips.push(<Chip key="sub">{subcategoryLabel}</Chip>)
  }

  // ── Detalle rows + Peso del mes ─────────────────────────────────────────────
  const dateRow: DetailRowSpec = {
    key: 'date',
    icon: <Calendar size={16} strokeWidth={2} aria-hidden />,
    label: tDetail('labels.date'),
    value: formatLongDate(movement.date),
  }

  const monthWeightTile = (() => {
    if (recurrence) return null
    if (!monthWeightSlices?.length) return null
    if (isIncome) {
      const pct = resolveIncomeWeight(monthWeightSlices, movement.amount)
      if (pct == null) return null
      return (
        <TileMonthWeight
          key="weight"
          pct={pct}
          cap={tDetail('month_weight.income_cap')}
          headline={tDetail('month_weight.income_headline')}
          note={tDetail('month_weight.income_note', { pct: Math.round(pct) })}
        />
      )
    }
    if (isExpense) {
      const w = resolveCategoryWeight(monthWeightSlices, movement.category_id, movement.amount)
      if (!w) return null
      return (
        <TileMonthWeight
          key="weight"
          pct={w.pct}
          cap={categoryLabel ?? tDetail('groups.month_weight')}
          headline={categoryLabel ?? tDetail('groups.month_weight')}
          note={
            <>
              {w.rank <= 5 && <b>{tDetail('month_weight.expense_rank', { rank: w.rank })}. </b>}
              {tDetail('month_weight.expense_note', {
                share: Math.round(w.shareOfCategoryPct),
                cap: categoryLabel ?? '',
              })}
            </>
          }
        />
      )
    }
    return null
  })()

  // ── Tiles by variant ────────────────────────────────────────────────────────
  const tiles: ReactNode[] = []

  if (isTransferLike) {
    tiles.push(
      <TileTransferFlow
        key="flow"
        source={transaction.source_account}
        destination={transaction.destination_account}
      />,
      <TileTransferCallout key="callout" />,
    )
    const rows: DetailRowSpec[] = [
      {
        key: 'amount',
        icon: <Banknote size={16} strokeWidth={2} aria-hidden />,
        label: t('labels.amount'),
        value: <span className="tabular-nums">{money(movement.amount)}</span>,
      },
    ]
    if (movement.kind === 'exchange') {
      rows.push({
        key: 'received',
        icon: <Coins size={16} strokeWidth={2} aria-hidden />,
        label: t('labels.exchange_received'),
        value: (
          <span className="tabular-nums text-income">
            +{money(movement.destination_amount, movement.destination_currency)}
          </span>
        ),
      })
    } else {
      rows.push({
        key: 'status',
        icon: <Check size={16} strokeWidth={2} aria-hidden />,
        label: t('labels.status'),
        value: <StatusDot label={tDetail('status.completed')} />,
      })
    }
    tiles.push(<TileDetail key="detail" rows={rows} span2 />)
  } else if (recurrence) {
    tiles.push(
      <TileRecurrence key="rec" summary={recurrence} />,
      <TilePaymentMethod
        key="paid"
        account={transaction.source_account}
        meta={
          <>
            <Repeat aria-hidden />
            {t('detail.recurrence.eyebrow')}:{' '}
            <b className="tabular-nums">{money(recurrence.accumulated, recurrence.currency)}</b>
          </>
        }
      />,
      <TileRecurrenceHistory key="hist" summary={recurrence} />,
    )
  } else if (isInstallment) {
    const parentAmount = installmentParent?.amount ?? movement.amount
    tiles.push(
      <TileInstallments
        key="cuotas"
        children_={installmentSiblings ?? []}
        parentAmount={parentAmount}
        currency={movement.currency_code}
        currentN={transaction.installment_n}
      />,
      <TilePaymentMethod key="paid" account={transaction.source_account} />,
      <TileDetail
        key="detail"
        rows={[
          {
            key: 'total',
            icon: <Coins size={16} strokeWidth={2} aria-hidden />,
            label: t('card_purchase_total'),
            value: <span className="tabular-nums">{money(parentAmount)}</span>,
            rightLabel: tDetail('installments.eyebrow'),
            rightValue:
              installmentSiblings && installmentSiblings.length > 0
                ? `${installmentSiblings.length} × ${money(installmentSiblings[0]!.amount)}`
                : undefined,
          },
        ]}
      />,
    )
  } else if (hasReimbursements) {
    const received = reimbursements.some((r) => r.state === 'received')
    tiles.push(
      <TileReimbursementNet
        key="net"
        paid={movement.amount}
        currency={movement.currency_code}
        reimbursements={reimbursements}
      />,
      <TilePaymentMethod key="paid" account={transaction.source_account} />,
      <TileDetail
        key="detail"
        rows={[
          {
            key: 'status',
            icon: <Check size={16} strokeWidth={2} aria-hidden />,
            label: t('labels.status'),
            value: received ? (
              <StatusDot label={tDetail('status.reimbursed')} />
            ) : (
              <span className="text-text-muted">{t('reimbursement.state.pending')}</span>
            ),
          },
        ]}
      />,
    )
  } else if (isShared) {
    tiles.push(
      <TileShareYours key="yours" shared={sharedInfo!} total={movement.amount} currency={movement.currency_code} />,
      <TilePaymentMethod key="paid" account={transaction.source_account} />,
      <TileDividedAmong key="among" shared={sharedInfo!} currency={movement.currency_code} />,
      <TileDetail
        key="detail"
        span2
        rows={[
          {
            key: 'total',
            icon: <Coins size={16} strokeWidth={2} aria-hidden />,
            label: t('labels.amount') ?? 'Total',
            value: <span className="tabular-nums">{money(movement.amount)}</span>,
            rightLabel: tDetail('shared.your_share'),
            rightValue: money(sharedInfo!.ownShare),
          },
        ]}
      />,
    )
  } else if (isIncome) {
    tiles.push(
      <TilePaymentMethod
        key="paid"
        account={transaction.source_account}
        eyebrow={tDetail('groups.credited_to')}
      />,
      <TileDetail
        key="detail"
        span2
        rows={[
          dateRow,
          {
            key: 'status',
            icon: <Check size={16} strokeWidth={2} aria-hidden />,
            label: t('labels.status'),
            value: <StatusDot label={tDetail('status.credited')} />,
          },
        ]}
      />,
    )
  } else if (movement.kind === 'reimbursement') {
    tiles.push(
      <TilePaymentMethod key="paid" account={transaction.source_account} />,
      <TileDetail
        key="detail"
        span2
        rows={[
          dateRow,
          ...(transaction.linked_expense
            ? [
                {
                  key: 'linked',
                  icon: <Receipt size={16} strokeWidth={2} aria-hidden />,
                  label: t('reimbursement.linked_expense_title'),
                  value: (
                    <Link className="text-slate hover:underline" href={`/transactions/${transaction.linked_expense.id}`}>
                      {transaction.linked_expense.description ??
                        transaction.linked_expense.category?.name ??
                        t('types.expense')}
                    </Link>
                  ),
                } satisfies DetailRowSpec,
              ]
            : []),
        ]}
      />,
    )
  } else {
    // generic: expense simple, card_payment, adjustment, settlement
    const rows: DetailRowSpec[] = [dateRow]
    if (movement.kind === 'card_payment' && paymentComposition) {
      rows.push({
        key: 'composition_ars',
        icon: <Banknote size={16} strokeWidth={2} aria-hidden />,
        label: t('detail.labels.composition_ars'),
        value: <span className="tabular-nums">{money(paymentComposition.paidARS, 'ARS')}</span>,
      })
      if (paymentComposition.paidUSD > 0) {
        rows.push({
          key: 'composition_usd',
          icon: <Banknote size={16} strokeWidth={2} aria-hidden />,
          label: t('detail.labels.composition_usd'),
          value: <span className="tabular-nums">{money(paymentComposition.paidUSD, 'USD')}</span>,
        })
      }
    }
    if (transaction.fx_rate_to_ars) {
      rows.push({
        key: 'fx',
        icon: <Hash size={16} strokeWidth={2} aria-hidden />,
        label: t('detail.labels.fx_rate'),
        value: t('fx_rate_template', { rate: transaction.fx_rate_to_ars }),
      })
    }
    tiles.push(
      <TilePaymentMethod key="paid" account={transaction.source_account} />,
      <TileDetail key="detail" rows={rows} />,
    )
  }

  // Descripción + Peso en el mes (siempre al final)
  tiles.push(<TileDescription key="desc" description={transaction.description} />)
  if (monthWeightTile) tiles.push(monthWeightTile)

  return (
    <div style={toneVars(detailTone)} className="mx-auto w-full max-w-[760px] pb-24 sm:pb-2">
      <DetailTopbar
        backHref={backFor(from)}
        backLabel={t('back_label')}
        actions={
          actionAccountId ? (
            <DetailActions
              transactionId={transaction.id}
              canEdit={canEdit}
              canDelete={canDelete}
              isParent={transaction.is_parent}
              isCardPayment={!!transaction.period_payments?.[0]}
              onEdit={canUseEditDrawer ? () => setEditOpen(true) : undefined}
            />
          ) : undefined
        }
      />

      {canUseEditDrawer && (
        <Drawer open={editOpen} onClose={() => setEditOpen(false)} ariaLabel={t('edit_title')}>
          <MovementForm
            variant="drawer"
            accounts={[]}
            categories={editCategories!}
            edit={edit!}
            household={editHouseholdResolved}
            onClose={() => setEditOpen(false)}
            onSuccess={() => setEditOpen(false)}
          />
        </Drawer>
      )}

      <div className="flex flex-col gap-3.5 sm:gap-[18px]">
        <DetailHero
          tone={tone}
          icon={heroIcon(movement)}
          amount={movement.amount}
          currency={movement.currency_code}
          eyebrow={isTransferLike ? tDetail('transfer.internal') : undefined}
          title={heroTitle}
          flow={flowLine}
          chips={chips}
        />

        {contextCopy && (
          <Alert variant="info" icon={false}>
            {contextCopy}
          </Alert>
        )}

        {installmentParentHref && (
          <Alert variant="info" icon={false}>
            {tDetail('installment_child_note')}{' '}
            <Link href={installmentParentHref} className="font-semibold underline">
              {tDetail('installment_child_link')}
            </Link>
          </Alert>
        )}

        {movement.review_flags.length > 0 && (
          <div className="flex items-start gap-2 rounded-[14px] border border-warning-soft bg-warning-bg px-3.5 py-3 text-sm text-warning-deep">
            <AlertTriangle className="mt-0.5 shrink-0" size={16} aria-hidden />
            <div>
              <p className="font-semibold">{t('review_alert_title')}</p>
              <p>{movement.review_flags.map((flag) => reviewLabel[flag]).join(' · ')}</p>
            </div>
          </div>
        )}

        <Glance>{tiles}</Glance>
      </div>
    </div>
  )
}
