import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const cssPath = path.join(__dirname, '../src/theme.css')
const outPath = path.join(__dirname, '../src/tokens.cjs')
// A diferencia de `tokens.cjs`, este archivo se emite en la raíz del package y
// no en `src/`: `postcss-import` (que corre dentro del pipeline de Tailwind v3
// de mobile) resuelve subpaths literales contra `node_modules/<pkg>/…` y NO lee
// el mapa `exports` del `package.json`. En la raíz, `@grana/ui-tokens/tokens.css`
// funciona con los dos resolvers.
const cssOutPath = path.join(__dirname, '../tokens.css')

const css = readFileSync(cssPath, 'utf8')

function extractVarsFromBlock(blockContent) {
  const vars = {}
  for (const line of blockContent.split('\n')) {
    const m = line.match(/^\s*--([\w-]+):\s*([^;]+);/)
    if (m) vars[m[1]] = m[2].trim()
  }
  return vars
}

const rootMatch = css.match(/:root\s*\{([^}]+)\}/)
const darkMatch = css.match(/\.dark\s*\{([^}]+)\}/)

const light = rootMatch ? extractVarsFromBlock(rootMatch[1]) : {}
const dark = darkMatch ? extractVarsFromBlock(darkMatch[1]) : {}

const colors = {}
for (const [key, value] of Object.entries(light)) {
  colors[key] = { DEFAULT: value }
  if (dark[key]) colors[key].dark = dark[key]
}

const output = `module.exports = ${JSON.stringify({ colors }, null, 2)};\n`
writeFileSync(outPath, output)
console.log(`tokens.cjs written with ${Object.keys(colors).length} colors`)

// `tokens.css` es el mismo `:root` de `theme.css` pero sin la sintaxis de
// Tailwind v4 (`@custom-variant`, `@theme`), que Tailwind v3 no entiende.
// Lo consume `apps/mobile/global.css`: sin estas custom properties, toda clase
// cuyo token sea un alias (`bg-background`, `text-muted`, …) compila a un
// `var(--…)` que React Native no puede resolver y no pinta.
//
// El bloque `.dark` queda fuera a propósito: la app mobile es light-only
// (`userInterfaceStyle: "light"` en `app.json`).
const cssLines = Object.entries(light).map(([key, value]) => `  --${key}: ${value};`)
const cssOutput = `/* GENERATED by scripts/codegen.mjs from theme.css — do not edit by hand. */\n\n:root {\n${cssLines.join('\n')}\n}\n`
writeFileSync(cssOutPath, cssOutput)
console.log(`tokens.css written with ${cssLines.length} custom properties`)
