'use client'

import {
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  Coins,
  CreditCard,
  Repeat,
  Scale,
  Tag,
  Users,
} from 'lucide-react'
import { useTranslations } from 'next-intl'
import { formatARS, formatUSD } from '@grana/i18n-messages'
import {
  resolveMovementView,
  type MovementPerspective,
  type MovementKind,
} from '@grana/money-logic'
import { useShowCents } from '@/lib/preferences-context'
import { translateCategoryLabel, translateSubcategoryLabel } from '@/lib/categories/display'
import { toMovementViewInput, type FinancialMovement } from '../movements'
import { resolveTone, toneToClass } from './tone'

/** Lucide icon for the "structure" family (movements with no category). */
const structureIcon: Partial<Record<MovementKind, typeof Tag>> = {
  transfer: ArrowLeftRight,
  exchange: Coins,
  adjustment: Scale,
  card_payment: CreditCard,
}

/** Fallback icon for categorized movements without a category emoji. */
const categorizedFallbackIcon: Partial<Record<MovementKind, typeof Tag>> = {
  income: ArrowDownLeft,
  expense: Tag,
  installment_purchase: CreditCard,
  reimbursement: ArrowDownLeft,
}

const typeLabelKey: Record<MovementKind, string> = {
  income: 'types.income',
  expense: 'types.expense',
  transfer: 'types.transfer',
  adjustment: 'types.adjustment',
  exchange: 'types.exchange',
  card_payment: 'card_payment_label',
  installment_purchase: 'installment_purchase_label',
  reimbursement: 'reimbursement.label',
}

const formatAmount = (amount: number, currency: 'ARS' | 'USD', showCents: boolean) =>
  currency === 'ARS' ? formatARS(amount, showCents) : formatUSD(amount, showCents)

type Props = {
  movement: FinancialMovement
  perspective: MovementPerspective
  /** Show the account in the subtitle (only when the user has multiple accounts). */
  showAccount?: boolean
  /** Whether this movement was generated by a recurrence rule. */
  isRecurrent?: boolean
  /** Running balance after this movement, per currency (account view, no filters). */
  runningBalanceSnapshot?: Record<'ARS' | 'USD', number> | null
  /** Installment chip label (e.g. "Cuota 2 de 6"); shown on card-statement rows. */
  installmentChip?: string | null
  /** Render the installment chip on its own line below the subtitle (card statement layout). */
  installmentChipBelow?: boolean
}

export const MovementRow = ({
  movement,
  perspective,
  showAccount = false,
  isRecurrent = false,
  runningBalanceSnapshot = null,
  installmentChip = null,
  installmentChipBelow = false,
}: Props) => {
  const t = useTranslations('transactions')
  const tRoot = useTranslations()
  const showCents = useShowCents()

  const view = resolveMovementView(toMovementViewInput(movement), perspective)
  const typeLabel = t(typeLabelKey[movement.kind])

  // System categories/subcategories render localized; user-owned keep their name.
  const categoryLabel = translateCategoryLabel(
    movement.category_name,
    movement.category_canonical_name,
    movement.category_is_system,
    tRoot,
  )
  const subcategoryLabel = translateSubcategoryLabel(
    movement.subcategory_name,
    movement.subcategory_canonical_name,
    movement.subcategory_is_system,
    tRoot,
  )

  // Installment purchases always carry their cuotas count as a chip, so the
  // list says "en cuotas" even when the host doesn't inject per-row chips
  // (the card-period view injects "Cuota X de Y" for the children instead).
  const chip =
    installmentChip ??
    (movement.kind === 'installment_purchase' && movement.installments_total
      ? t('installments_count', { count: movement.installments_total })
      : null)
  const runningBalance = runningBalanceSnapshot ? runningBalanceSnapshot[view.currencyCode] : null
  const isPendingReimbursement =
    movement.kind === 'reimbursement' && movement.state !== 'received'

  // Primary line: what the user wrote; falls back to the category or type name.
  // Adjustments carry a meaningful title (real "Ajuste", or a settlement label
  // like "Pago de deuda compartida"), so prefer it over the generic type label.
  const fallbackLabel = view.isCategorized ? categoryLabel ?? typeLabel : typeLabel
  const primary =
    movement.description ?? (movement.kind === 'adjustment' ? movement.title : fallbackLabel)

  // Account display: institution leads, the account's own name is the fallback
  // (cash/wallet accounts have no institution). Keeps the compact row to one
  // line while matching the "institution principal" treatment elsewhere.
  const accountLabel = (name: string | null, institutionName: string | null | undefined): string =>
    institutionName?.trim() || name || '?'

  // Secondary line depends on the family.
  const secondary = ((): string | null => {
    if (movement.kind === 'transfer' || movement.kind === 'exchange') {
      const sourceLabel = accountLabel(movement.account_name, movement.account_institution_name)
      const destLabel = accountLabel(movement.destination_account_name, movement.destination_account_institution_name)
      if (view.counterpartyDirection === 'in') return `← ${sourceLabel}`
      if (view.counterpartyDirection === 'out' && perspective.kind === 'account') {
        return `→ ${destLabel}`
      }
      // global: show both ends
      return `${sourceLabel} → ${destLabel}`
    }
    if (movement.kind === 'card_payment') {
      return movement.account_name
        ? t('list.card_payment_from', { accountName: accountLabel(movement.account_name, movement.account_institution_name) })
        : null
    }
    // Categorized line. The category only repeats here when the description
    // already takes the primary slot; otherwise it's already the primary and
    // the secondary leads with the subcategory (when set).
    const taxonomy = movement.description
      ? subcategoryLabel
        ? `${categoryLabel} › ${subcategoryLabel}`
        : categoryLabel
      : subcategoryLabel
    const parts: string[] = []
    if (taxonomy) parts.push(taxonomy)
    if (showAccount && movement.account_name) {
      parts.push(accountLabel(movement.account_name, movement.account_institution_name))
    }
    return parts.length > 0 ? parts.join(' · ') : null
  })()

  const CategoryEmoji = view.isCategorized && movement.category_icon
  const FallbackIcon =
    structureIcon[movement.kind] ?? categorizedFallbackIcon[movement.kind] ?? Tag

  // Layout — the amount always stays inline with the title (web parity on every
  // width), right-aligned in its own column; the title truncates (`min-w-0`)
  // instead of fighting it.
  //   • With running balance (account / card statement): 2 cols on mobile
  //     (running balance hidden), 3 cols ≥md.
  //   • Without running balance (/transactions, generic list): 2 cols, the
  //     amount column sized to its content.
  const gridCls = runningBalance != null
    ? 'grid grid-cols-[minmax(0,1fr)_112px] md:grid-cols-[minmax(0,1fr)_126px_126px] items-center gap-4 md:gap-[18px] min-h-[62px] px-4 py-3 hover:bg-muted/40 transition-colors'
    : 'grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 sm:gap-[18px] min-h-[62px] px-4 py-3 hover:bg-muted/40 transition-colors'

  const amountCls = 'text-right'

  return (
    <div className={gridCls}>
      <div className="flex min-w-0 items-center gap-2.5">
        {CategoryEmoji ? (
          <span
            className="grid h-9 w-9 shrink-0 place-items-center rounded-xl text-base"
            style={{ backgroundColor: `${movement.category_color ?? '#888'}1A` }}
          >
            {movement.category_icon}
          </span>
        ) : (
          <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-muted text-muted-foreground">
            <FallbackIcon size={17} />
          </span>
        )}

        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
            <span className="min-w-0 truncate text-[13px] font-extrabold leading-tight">{primary}</span>
            {chip && !installmentChipBelow && (
              <span className="inline-flex shrink-0 items-center rounded-full bg-border-soft px-1.5 py-0.5 text-[11px] font-semibold text-text-muted">
                {chip}
              </span>
            )}
            {isRecurrent && (
              <span
                className="inline-flex shrink-0 items-center gap-1 rounded-full bg-slate-soft px-1.5 py-0.5 text-[11px] font-semibold text-slate"
                aria-label={t('generated_by_rule')}
              >
                <Repeat size={10} />
                {t('list.recurrent_short')}
              </span>
            )}
            {movement.review_flags.length > 0 && (
              <span className="inline-flex shrink-0 items-center gap-1 rounded-md bg-amber-100 px-1.5 py-0.5 text-[11px] font-medium text-amber-800">
                <AlertTriangle size={12} />
                {t('list.review_short')}
              </span>
            )}
            {movement.isShared && (
              <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-border-soft px-1.5 py-0.5 text-[11px] font-semibold text-text-muted">
                <Users size={10} />
                {t('list.shared_short')}
              </span>
            )}
            {movement.kind === 'reimbursement' && (
              <span
                className={`inline-flex shrink-0 items-center rounded-md px-1.5 py-0.5 text-[11px] font-medium ${
                  movement.state === 'received'
                    ? 'bg-green-100 text-green-800'
                    : movement.state === 'cancelled'
                      ? 'bg-muted text-muted-foreground line-through'
                      : 'bg-amber-100 text-amber-800'
                }`}
              >
                {t(`reimbursement.state.${movement.state}`)}
              </span>
            )}
          </div>
          {secondary && (
            <p className="mt-0.5 truncate text-xs text-muted-foreground">{secondary}</p>
          )}
          {chip && installmentChipBelow && (
            <span className="mt-1.5 inline-flex items-center rounded-full bg-border-soft px-2 py-0.5 text-[11px] font-bold text-text-muted">
              {chip}
            </span>
          )}
        </div>
      </div>

      <div className={amountCls}>
        <p
          className={`text-[14px] font-extrabold tabular-nums ${toneToClass(resolveTone(movement.kind, view.sign, isPendingReimbursement))}`}
        >
          {view.sign}
          {formatAmount(view.amount, view.currencyCode, showCents)}
        </p>
        {view.currencyCode === 'USD' && (
          <p className="text-[11px] font-normal text-muted-foreground">USD</p>
        )}
      </div>

      {runningBalance != null && (
        <div className="hidden text-right text-[12px] font-bold text-muted-foreground tabular-nums md:block">
          {formatAmount(runningBalance, view.currencyCode, showCents)}
        </div>
      )}
    </div>
  )
}
