'use client'

import {
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  Coins,
  CreditCard,
  Repeat,
  Scale,
  Tag,
} from 'lucide-react'
import { useTranslations } from 'next-intl'
import { formatARS, formatUSD } from '@grana/i18n-messages'
import {
  resolveMovementView,
  type MovementPerspective,
  type MovementKind,
} from '@grana/money-logic'
import { useShowCents } from '@/lib/preferences-context'
import { toMovementViewInput, type FinancialMovement } from '../movements'
import { resolveTone, toneToClass } from './tone'

/** Lucide icon for the "structure" family (movements with no category). */
const structureIcon: Partial<Record<MovementKind, typeof Tag>> = {
  transfer: ArrowLeftRight,
  exchange: Coins,
  adjustment: Scale,
  card_payment: CreditCard,
}

/** Fallback icon for categorized movements without a category emoji. */
const categorizedFallbackIcon: Partial<Record<MovementKind, typeof Tag>> = {
  income: ArrowDownLeft,
  expense: Tag,
  installment_purchase: CreditCard,
  reimbursement: ArrowDownLeft,
}

const typeLabelKey: Record<MovementKind, string> = {
  income: 'types.income',
  expense: 'types.expense',
  transfer: 'types.transfer',
  adjustment: 'types.adjustment',
  exchange: 'types.exchange',
  card_payment: 'card_payment_label',
  installment_purchase: 'installment_purchase_label',
  reimbursement: 'reimbursement.label',
}

const formatAmount = (amount: number, currency: 'ARS' | 'USD', showCents: boolean) =>
  currency === 'ARS' ? formatARS(amount, showCents) : formatUSD(amount, showCents)

type Props = {
  movement: FinancialMovement
  perspective: MovementPerspective
  /** Show the account in the subtitle (only when the user has multiple accounts). */
  showAccount?: boolean
  /** Whether this movement was generated by a recurrence rule. */
  isRecurrent?: boolean
  /** Running balance after this movement, per currency (account view, no filters). */
  runningBalanceSnapshot?: Record<'ARS' | 'USD', number> | null
  /** Installment chip label (e.g. "Cuota 2 de 6"); shown on card-statement rows. */
  installmentChip?: string | null
}

export const MovementRow = ({
  movement,
  perspective,
  showAccount = false,
  isRecurrent = false,
  runningBalanceSnapshot = null,
  installmentChip = null,
}: Props) => {
  const t = useTranslations('transactions')
  const showCents = useShowCents()

  const view = resolveMovementView(toMovementViewInput(movement), perspective)
  const typeLabel = t(typeLabelKey[movement.kind])
  const runningBalance = runningBalanceSnapshot ? runningBalanceSnapshot[view.currencyCode] : null
  const isPendingReimbursement =
    movement.kind === 'reimbursement' && movement.state !== 'received'

  // Primary line: what the user wrote; falls back to the category or type name.
  const fallbackLabel = view.isCategorized ? movement.category_name ?? typeLabel : typeLabel
  const primary = movement.description ?? fallbackLabel

  // Secondary line depends on the family.
  const secondary = ((): string | null => {
    if (movement.kind === 'transfer' || movement.kind === 'exchange') {
      if (view.counterpartyDirection === 'in') return `← ${view.counterpartyName ?? '?'}`
      if (view.counterpartyDirection === 'out' && perspective.kind === 'account') {
        return `→ ${view.counterpartyName ?? '?'}`
      }
      // global: show both ends
      return `${movement.account_name ?? '?'} → ${view.counterpartyName ?? '?'}`
    }
    if (movement.kind === 'card_payment') {
      return movement.account_name ? t('list.card_payment_from', { accountName: movement.account_name }) : null
    }
    // Categorized line. The category only repeats here when the description
    // already takes the primary slot; otherwise it's already the primary and
    // the secondary leads with the subcategory (when set).
    const taxonomy = movement.description
      ? movement.subcategory_name
        ? `${movement.category_name} › ${movement.subcategory_name}`
        : movement.category_name
      : movement.subcategory_name
    const parts: string[] = []
    if (taxonomy) parts.push(taxonomy)
    if (showAccount && movement.account_name) parts.push(movement.account_name)
    return parts.length > 0 ? parts.join(' · ') : null
  })()

  const CategoryEmoji = view.isCategorized && movement.category_icon
  const FallbackIcon =
    structureIcon[movement.kind] ?? categorizedFallbackIcon[movement.kind] ?? Tag

  return (
    <div className="flex items-center justify-between gap-4 px-4 py-3 hover:bg-muted/50 transition-colors">
      <div className="flex min-w-0 items-center gap-3">
        {CategoryEmoji ? (
          <span
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md text-base"
            style={{ backgroundColor: `${movement.category_color ?? '#888'}1A` }}
          >
            {movement.category_icon}
          </span>
        ) : (
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground">
            <FallbackIcon size={17} />
          </span>
        )}

        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <span className="truncate text-sm font-bold">{primary}</span>
            {installmentChip && (
              <span className="inline-flex shrink-0 items-center rounded-full bg-border-soft px-1.5 py-0.5 text-[11px] font-semibold text-text-muted">
                {installmentChip}
              </span>
            )}
            {isRecurrent && (
              <span
                className="inline-flex shrink-0 items-center gap-1 rounded-full bg-slate-soft px-1.5 py-0.5 text-[11px] font-semibold text-slate"
                aria-label={t('generated_by_rule')}
              >
                <Repeat size={10} />
                {t('list.recurrent_short')}
              </span>
            )}
            {movement.review_flags.length > 0 && (
              <span className="inline-flex shrink-0 items-center gap-1 rounded-md bg-amber-100 px-1.5 py-0.5 text-[11px] font-medium text-amber-800">
                <AlertTriangle size={12} />
                {t('list.review_short')}
              </span>
            )}
            {movement.kind === 'reimbursement' && (
              <span
                className={`inline-flex shrink-0 items-center rounded-md px-1.5 py-0.5 text-[11px] font-medium ${
                  movement.state === 'received'
                    ? 'bg-green-100 text-green-800'
                    : movement.state === 'cancelled'
                      ? 'bg-muted text-muted-foreground line-through'
                      : 'bg-amber-100 text-amber-800'
                }`}
              >
                {t(`reimbursement.state.${movement.state}`)}
              </span>
            )}
          </div>
          {secondary && <p className="truncate text-xs text-muted-foreground">{secondary}</p>}
        </div>
      </div>

      <div className="shrink-0 text-right">
        <p className={`text-sm font-semibold tabular-nums ${toneToClass(resolveTone(movement.kind, view.sign, isPendingReimbursement))}`}>
          {view.sign}
          {formatAmount(view.amount, view.currencyCode, showCents)}
        </p>
        {view.currencyCode === 'USD' && (
          <p className="text-xs font-normal text-muted-foreground">USD</p>
        )}
        {runningBalance != null && (
          <p className="text-xs text-muted-foreground tabular-nums">
            {formatAmount(runningBalance, view.currencyCode, showCents)}
          </p>
        )}
      </div>
    </div>
  )
}
