-- Abbreviate the American Express network label to "Amex" so it always shows
-- abbreviated: the network label in the UI and any future autogenerated card
-- name (red + banco) will read "Amex <banco>" instead of "American Express
-- <banco>". The monogram (first letter) is unchanged ("A").
--
-- NOTE: card names already persisted on existing accounts are NOT modified by
-- this migration — only the network catalog label changes. Renaming existing
-- cards is a separate, user-data concern.

update card_networks set name = 'Amex' where slug = 'amex';
