-- Rename existing credit-card accounts whose name was autogenerated with the
-- old "American Express" network label (stored in accounts.name at creation,
-- e.g. "American Express Banco Galicia") so they read "Amex <banco>" like cards
-- created after 0032. Scoped to credit accounts; replaces the substring wherever
-- it appears in the name.

update accounts
set name = replace(name, 'American Express', 'Amex')
where type = 'credit'
  and name like '%American Express%';
